spring.application.name=jk-shop
server.port=${PORT:8080}

project.image=images/
image.base.url=${IMAGE_BASE_URL:http://localhost:8080/images}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.app.jwtSecret=${JWT_SECRET:mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}
spring.ecom.app.jwtCookieName=jk-shop

frontend.url=${FRONTEND_URL:http://localhost:5173}
stripe.secret.key=${STRIPE_SECRET_KEY}

