// Initial Redux state for Cart
const initialState = {
    // Products added to cart
    cart: [],
    // Total cart amount
    totalPrice: 0,
    // Cart ID generated by backend
    cartId: null,
};

export const cartReducer = (state = initialState, action) => {
    // Decide what update to perform
    switch (action.type) {
        
        // Add or Update Cart Product
        case "ADD_CART":
            // Product received from dispatch()
            const productToAdd = action.payload;
            // Check whether product already exists in cart
            const existingProduct = state.cart.find(
                (item) => item.productId === productToAdd.productId
            );
            // Product already exists
            if (existingProduct) {

                // Replace old product with updated product
                // (quantity, price etc. may have changed)
                const updatedCart = state.cart.map((item) => {

                    if (item.productId === productToAdd.productId) {
                        return productToAdd;

                    } else {
                        return item;
                    }
                });
                return {
                    ...state,

                    // Save updated cart
                    cart: updatedCart,
                };

            } else {

                // Product doesn't exist
                // Add it to cart array
                const newCart = [
                    ...state.cart,
                    productToAdd
                ];

                return {
                    ...state,

                    // Save new cart
                    cart: newCart,
                };
            }
        // Remove Product from Cart
        case "REMOVE_CART":
            return {
                ...state,
                // Keep every product except deleted one
                cart: state.cart.filter(
                    (item) =>
                        item.productId !== action.payload.productId
                ),
            };
        // Store Latest Cart
        // (Received from Backend)
        case "GET_USER_CART_PRODUCTS":
            return {
                ...state,
                // Cart items
                cart: action.payload,
                // Total amount
                totalPrice: action.totalPrice,
                // Backend Cart ID
                cartId: action.cartId,
            };
        // Clear Entire Cart
        case "CLEAR_CART":
            return {
                // Empty cart
                cart: [],
                // Reset price
                totalPrice: 0,
                // Remove cart id
                cartId: null,
            };
        // Unknown Action
        default:
            return state;
    }
    // (Never reached because switch always returns)
    return state;
}